// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    members,
    scans,
    topups,
    refunds,
    menuCategories,
    menuEntries,
    ingredients,
    recipes,
    purchaseScheduleItems,
    expenses,
    users,
    sessions,
    notifications,
    appSettings,
  ];
  late final Shape0 members = Shape0(
      source: i0.VersionedTable(
        entityName: 'members',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 scans = Shape1(
      source: i0.VersionedTable(
        entityName: 'scans',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 topups = Shape2(
      source: i0.VersionedTable(
        entityName: 'topups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
          _column_29,
          _column_30,
          _column_12,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 refunds = Shape3(
      source: i0.VersionedTable(
        entityName: 'refunds',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_22,
          _column_23,
          _column_24,
          _column_31,
          _column_32,
          _column_33,
          _column_12,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 menuCategories = Shape4(
      source: i0.VersionedTable(
        entityName: 'menu_categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_34,
          _column_35,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 menuEntries = Shape5(
      source: i0.VersionedTable(
        entityName: 'menu_entries',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_36,
          _column_15,
          _column_37,
          _column_38,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 ingredients = Shape6(
      source: i0.VersionedTable(
        entityName: 'ingredients',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_34,
          _column_39,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 recipes = Shape7(
      source: i0.VersionedTable(
        entityName: 'recipes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_40,
          _column_41,
          _column_42,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 purchaseScheduleItems = Shape8(
      source: i0.VersionedTable(
        entityName: 'purchase_schedule_items',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_36,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 expenses = Shape9(
      source: i0.VersionedTable(
        entityName: 'expenses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_51,
          _column_52,
          _column_25,
          _column_36,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 users = Shape10(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_53,
          _column_54,
          _column_55,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 sessions = Shape11(
      source: i0.VersionedTable(
        entityName: 'sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(token)',
        ],
        columns: [
          _column_56,
          _column_57,
          _column_58,
          _column_55,
          _column_12,
          _column_59,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 notifications = Shape12(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(type, date_key, meal_type)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_60,
          _column_61,
          _column_62,
          _column_63,
          _column_64,
          _column_65,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape13 appSettings = Shape13(
      source: i0.VersionedTable(
        entityName: 'app_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_66,
          _column_67,
          _column_68,
          _column_69,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_76,
          _column_77,
          _column_78,
          _column_79,
          _column_80,
          _column_81,
          _column_82,
          _column_83,
          _column_84,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get className =>
      columnsByName['class_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rollNumber =>
      columnsByName['roll_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get staffId =>
      columnsByName['staff_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get qrCodeId =>
      columnsByName['qr_code_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lunchBalance =>
      columnsByName['lunch_balance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get breakfastBalance =>
      columnsByName['breakfast_balance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get brunchBalance =>
      columnsByName['brunch_balance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graceAllowanceOverride =>
      columnsByName['grace_allowance_override']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT');
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('class_name', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('roll_number', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('staff_id', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('qr_code_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL UNIQUE');
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>('lunch_balance', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>('breakfast_balance', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('brunch_balance', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('grace_allowance_override', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>('status', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'active\'',
        defaultValue: const i1.CustomExpression('\'active\''));
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>('created_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>('updated_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberId =>
      columnsByName['member_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mealType =>
      columnsByName['meal_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get scannedAt =>
      columnsByName['scanned_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get result =>
      columnsByName['result']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get viaGrace =>
      columnsByName['via_grace']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reversed =>
      columnsByName['reversed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reversedAt =>
      columnsByName['reversed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reversedBy =>
      columnsByName['reversed_by']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>('member_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES members(id)');
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('meal_type', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>('scanned_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>('result', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'accepted\'',
        defaultValue: const i1.CustomExpression('\'accepted\''));
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('via_grace', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (via_grace IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('reversed', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (reversed IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>('reversed_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>('reversed_by', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberId =>
      columnsByName['member_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lunchUnits =>
      columnsByName['lunch_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get breakfastUnits =>
      columnsByName['breakfast_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get brunchUnits =>
      columnsByName['brunch_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get paymentMethod =>
      columnsByName['payment_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get paymentStatus =>
      columnsByName['payment_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get billPdfPath =>
      columnsByName['bill_pdf_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get upiQrPath =>
      columnsByName['upi_qr_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>('lunch_units', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>('breakfast_units', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>('brunch_units', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<double> _column_25(String aliasedName) =>
    i1.GeneratedColumn<double>('amount', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>('payment_method', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>('payment_status', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>('bill_pdf_path', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>('upi_qr_path', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('created_by', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberId =>
      columnsByName['member_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lunchUnits =>
      columnsByName['lunch_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get breakfastUnits =>
      columnsByName['breakfast_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get brunchUnits =>
      columnsByName['brunch_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get refundAmount =>
      columnsByName['refund_amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get reason =>
      columnsByName['reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get processedBy =>
      columnsByName['processed_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>('refund_amount', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>('reason', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>('processed_by', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL UNIQUE');
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>('description', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mealType =>
      columnsByName['meal_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoriesJson =>
      columnsByName['categories_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemsJson =>
      columnsByName['items_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>('date', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>('categories_json', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>('items_json', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get unit =>
      columnsByName['unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>('unit', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dishName =>
      columnsByName['dish_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dishNameLower =>
      columnsByName['dish_name_lower']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ingredientsJson =>
      columnsByName['ingredients_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>('dish_name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>('dish_name_lower', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL UNIQUE');
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>('ingredients_json', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ingredientId =>
      columnsByName['ingredient_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get ingredientName =>
      columnsByName['ingredient_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ingredientUnit =>
      columnsByName['ingredient_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quantityNote =>
      columnsByName['quantity_note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get purchased =>
      columnsByName['purchased']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get purchasedBy =>
      columnsByName['purchased_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get purchasedAt =>
      columnsByName['purchased_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>('ingredient_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES ingredients(id)');
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>('ingredient_name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>('ingredient_unit', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>('quantity_note', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>('source', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>('purchased', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (purchased IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>('purchased_by', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>('purchased_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>('category', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>('description', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get passwordHash =>
      columnsByName['password_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>('username', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL UNIQUE');
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>('password_hash', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>('role', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get token =>
      columnsByName['token']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expiresAt =>
      columnsByName['expires_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>('token', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>('user_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES users(id)');
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>('username', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>('expires_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dateKey =>
      columnsByName['date_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealType =>
      columnsByName['meal_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get message =>
      columnsByName['message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get visibleRolesJson =>
      columnsByName['visible_roles_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dismissedByJson =>
      columnsByName['dismissed_by_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>('date_key', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>('meal_type', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>('message', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>('visible_roles_json', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>('dismissed_by_json', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'[]\'',
        defaultValue: const i1.CustomExpression('\'[]\''));

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graceAllowanceEnabled =>
      columnsByName['grace_allowance_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graceAllowanceUnits =>
      columnsByName['grace_allowance_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reversalWindowMinutes =>
      columnsByName['reversal_window_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get breakfastStart =>
      columnsByName['breakfast_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get breakfastEnd =>
      columnsByName['breakfast_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lunchStart =>
      columnsByName['lunch_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lunchEnd =>
      columnsByName['lunch_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brunchStart =>
      columnsByName['brunch_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brunchEnd =>
      columnsByName['brunch_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localTimezone =>
      columnsByName['local_timezone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get upiId =>
      columnsByName['upi_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get upiPayeeName =>
      columnsByName['upi_payee_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lunchPrice =>
      columnsByName['lunch_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get breakfastPrice =>
      columnsByName['breakfast_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get brunchPrice =>
      columnsByName['brunch_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get appName =>
      columnsByName['app_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get prepLeadMinutes =>
      columnsByName['prep_lead_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get purchaseLeadDays =>
      columnsByName['purchase_lead_days']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>('grace_allowance_enabled', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 0 CHECK (grace_allowance_enabled IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>('grace_allowance_units', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>('reversal_window_minutes', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 10',
        defaultValue: const i1.CustomExpression('10'));
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>('breakfast_start', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'07:00\'',
        defaultValue: const i1.CustomExpression('\'07:00\''));
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>('breakfast_end', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'09:30\'',
        defaultValue: const i1.CustomExpression('\'09:30\''));
i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>('lunch_start', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'12:00\'',
        defaultValue: const i1.CustomExpression('\'12:00\''));
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>('lunch_end', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'14:30\'',
        defaultValue: const i1.CustomExpression('\'14:30\''));
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>('brunch_start', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'09:00\'',
        defaultValue: const i1.CustomExpression('\'09:00\''));
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>('brunch_end', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'12:00\'',
        defaultValue: const i1.CustomExpression('\'12:00\''));
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>('local_timezone', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'Asia/Kolkata\'',
        defaultValue: const i1.CustomExpression('\'Asia/Kolkata\''));
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>('upi_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'\'',
        defaultValue: const i1.CustomExpression('\'\''));
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>('upi_payee_name', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'\'',
        defaultValue: const i1.CustomExpression('\'\''));
i1.GeneratedColumn<double> _column_79(String aliasedName) =>
    i1.GeneratedColumn<double>('lunch_price', aliasedName, false,
        type: i1.DriftSqlType.double,
        $customConstraints: 'NOT NULL DEFAULT 0.0',
        defaultValue: const i1.CustomExpression('0.0'));
i1.GeneratedColumn<double> _column_80(String aliasedName) =>
    i1.GeneratedColumn<double>('breakfast_price', aliasedName, false,
        type: i1.DriftSqlType.double,
        $customConstraints: 'NOT NULL DEFAULT 0.0',
        defaultValue: const i1.CustomExpression('0.0'));
i1.GeneratedColumn<double> _column_81(String aliasedName) =>
    i1.GeneratedColumn<double>('brunch_price', aliasedName, false,
        type: i1.DriftSqlType.double,
        $customConstraints: 'NOT NULL DEFAULT 0.0',
        defaultValue: const i1.CustomExpression('0.0'));
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>('app_name', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'Tiffin\'',
        defaultValue: const i1.CustomExpression('\'Tiffin\''));
i1.GeneratedColumn<int> _column_83(String aliasedName) =>
    i1.GeneratedColumn<int>('prep_lead_minutes', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 60',
        defaultValue: const i1.CustomExpression('60'));
i1.GeneratedColumn<int> _column_84(String aliasedName) =>
    i1.GeneratedColumn<int>('purchase_lead_days', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 1',
        defaultValue: const i1.CustomExpression('1'));

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    members,
    scans,
    topups,
    refunds,
    menuCategories,
    menuEntries,
    ingredients,
    recipes,
    purchaseScheduleItems,
    expenses,
    users,
    sessions,
    notifications,
    appSettings,
  ];
  late final Shape0 members = Shape0(
      source: i0.VersionedTable(
        entityName: 'members',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 scans = Shape1(
      source: i0.VersionedTable(
        entityName: 'scans',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 topups = Shape2(
      source: i0.VersionedTable(
        entityName: 'topups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
          _column_29,
          _column_30,
          _column_12,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 refunds = Shape3(
      source: i0.VersionedTable(
        entityName: 'refunds',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_22,
          _column_23,
          _column_24,
          _column_31,
          _column_32,
          _column_33,
          _column_12,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 menuCategories = Shape4(
      source: i0.VersionedTable(
        entityName: 'menu_categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_34,
          _column_35,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 menuEntries = Shape5(
      source: i0.VersionedTable(
        entityName: 'menu_entries',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_36,
          _column_15,
          _column_37,
          _column_38,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 ingredients = Shape6(
      source: i0.VersionedTable(
        entityName: 'ingredients',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_34,
          _column_39,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 recipes = Shape7(
      source: i0.VersionedTable(
        entityName: 'recipes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_40,
          _column_41,
          _column_42,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 purchaseScheduleItems = Shape8(
      source: i0.VersionedTable(
        entityName: 'purchase_schedule_items',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_36,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 expenses = Shape9(
      source: i0.VersionedTable(
        entityName: 'expenses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_51,
          _column_52,
          _column_25,
          _column_36,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 users = Shape10(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_53,
          _column_54,
          _column_55,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 sessions = Shape11(
      source: i0.VersionedTable(
        entityName: 'sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(token)',
        ],
        columns: [
          _column_56,
          _column_57,
          _column_58,
          _column_55,
          _column_12,
          _column_59,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 notifications = Shape12(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(type, date_key, meal_type)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_60,
          _column_61,
          _column_62,
          _column_63,
          _column_64,
          _column_65,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape14 appSettings = Shape14(
      source: i0.VersionedTable(
        entityName: 'app_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_66,
          _column_67,
          _column_68,
          _column_69,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_76,
          _column_77,
          _column_78,
          _column_79,
          _column_80,
          _column_81,
          _column_82,
          _column_83,
          _column_84,
          _column_85,
          _column_86,
          _column_87,
          _column_88,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graceAllowanceEnabled =>
      columnsByName['grace_allowance_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graceAllowanceUnits =>
      columnsByName['grace_allowance_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reversalWindowMinutes =>
      columnsByName['reversal_window_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get breakfastStart =>
      columnsByName['breakfast_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get breakfastEnd =>
      columnsByName['breakfast_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lunchStart =>
      columnsByName['lunch_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lunchEnd =>
      columnsByName['lunch_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brunchStart =>
      columnsByName['brunch_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brunchEnd =>
      columnsByName['brunch_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localTimezone =>
      columnsByName['local_timezone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get upiId =>
      columnsByName['upi_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get upiPayeeName =>
      columnsByName['upi_payee_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lunchPrice =>
      columnsByName['lunch_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get breakfastPrice =>
      columnsByName['breakfast_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get brunchPrice =>
      columnsByName['brunch_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get appName =>
      columnsByName['app_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get prepLeadMinutes =>
      columnsByName['prep_lead_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get purchaseLeadDays =>
      columnsByName['purchase_lead_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enforceAppearance =>
      columnsByName['enforce_appearance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get appearanceTheme =>
      columnsByName['appearance_theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get appearanceMode =>
      columnsByName['appearance_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get appearanceMotion =>
      columnsByName['appearance_motion']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_85(String aliasedName) =>
    i1.GeneratedColumn<int>('enforce_appearance', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 0 CHECK (enforce_appearance IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>('appearance_theme', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'neobrutal\'',
        defaultValue: const i1.CustomExpression('\'neobrutal\''));
i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>('appearance_mode', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'system\'',
        defaultValue: const i1.CustomExpression('\'system\''));
i1.GeneratedColumn<int> _column_88(String aliasedName) =>
    i1.GeneratedColumn<int>('appearance_motion', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 1 CHECK (appearance_motion IN (0, 1))',
        defaultValue: const i1.CustomExpression('1'));

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    members,
    scans,
    topups,
    refunds,
    menuCategories,
    menuEntries,
    ingredients,
    recipes,
    purchaseScheduleItems,
    expenses,
    users,
    sessions,
    notifications,
    appSettings,
  ];
  late final Shape0 members = Shape0(
      source: i0.VersionedTable(
        entityName: 'members',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 scans = Shape1(
      source: i0.VersionedTable(
        entityName: 'scans',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 topups = Shape2(
      source: i0.VersionedTable(
        entityName: 'topups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
          _column_29,
          _column_30,
          _column_12,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 refunds = Shape3(
      source: i0.VersionedTable(
        entityName: 'refunds',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_22,
          _column_23,
          _column_24,
          _column_31,
          _column_32,
          _column_33,
          _column_12,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 menuCategories = Shape4(
      source: i0.VersionedTable(
        entityName: 'menu_categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_34,
          _column_35,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 menuEntries = Shape5(
      source: i0.VersionedTable(
        entityName: 'menu_entries',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_36,
          _column_15,
          _column_37,
          _column_38,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 ingredients = Shape6(
      source: i0.VersionedTable(
        entityName: 'ingredients',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_34,
          _column_39,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 recipes = Shape7(
      source: i0.VersionedTable(
        entityName: 'recipes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_40,
          _column_41,
          _column_42,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 purchaseScheduleItems = Shape8(
      source: i0.VersionedTable(
        entityName: 'purchase_schedule_items',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_36,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 expenses = Shape9(
      source: i0.VersionedTable(
        entityName: 'expenses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_51,
          _column_52,
          _column_25,
          _column_36,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 users = Shape10(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_53,
          _column_54,
          _column_55,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 sessions = Shape11(
      source: i0.VersionedTable(
        entityName: 'sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(token)',
        ],
        columns: [
          _column_56,
          _column_57,
          _column_58,
          _column_55,
          _column_12,
          _column_59,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 notifications = Shape12(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(type, date_key, meal_type)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_60,
          _column_61,
          _column_62,
          _column_63,
          _column_64,
          _column_65,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape15 appSettings = Shape15(
      source: i0.VersionedTable(
        entityName: 'app_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_66,
          _column_67,
          _column_68,
          _column_69,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_76,
          _column_77,
          _column_78,
          _column_79,
          _column_80,
          _column_81,
          _column_82,
          _column_83,
          _column_84,
          _column_89,
          _column_85,
          _column_86,
          _column_87,
          _column_88,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graceAllowanceEnabled =>
      columnsByName['grace_allowance_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graceAllowanceUnits =>
      columnsByName['grace_allowance_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reversalWindowMinutes =>
      columnsByName['reversal_window_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get breakfastStart =>
      columnsByName['breakfast_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get breakfastEnd =>
      columnsByName['breakfast_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lunchStart =>
      columnsByName['lunch_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lunchEnd =>
      columnsByName['lunch_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brunchStart =>
      columnsByName['brunch_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brunchEnd =>
      columnsByName['brunch_end']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localTimezone =>
      columnsByName['local_timezone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get upiId =>
      columnsByName['upi_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get upiPayeeName =>
      columnsByName['upi_payee_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lunchPrice =>
      columnsByName['lunch_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get breakfastPrice =>
      columnsByName['breakfast_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get brunchPrice =>
      columnsByName['brunch_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get appName =>
      columnsByName['app_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get prepLeadMinutes =>
      columnsByName['prep_lead_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get purchaseLeadDays =>
      columnsByName['purchase_lead_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get hostId =>
      columnsByName['host_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get enforceAppearance =>
      columnsByName['enforce_appearance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get appearanceTheme =>
      columnsByName['appearance_theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get appearanceMode =>
      columnsByName['appearance_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get appearanceMotion =>
      columnsByName['appearance_motion']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>('host_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'\'',
        defaultValue: const i1.CustomExpression('\'\''));

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    members,
    scans,
    topups,
    refunds,
    menuCategories,
    menuEntries,
    ingredients,
    recipes,
    purchaseScheduleItems,
    expenses,
    users,
    sessions,
    notifications,
    appSettings,
  ];
  late final Shape0 members = Shape0(
      source: i0.VersionedTable(
        entityName: 'members',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 scans = Shape1(
      source: i0.VersionedTable(
        entityName: 'scans',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape16 topups = Shape16(
      source: i0.VersionedTable(
        entityName: 'topups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
          _column_29,
          _column_30,
          _column_12,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 refunds = Shape3(
      source: i0.VersionedTable(
        entityName: 'refunds',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_14,
          _column_22,
          _column_23,
          _column_24,
          _column_31,
          _column_32,
          _column_33,
          _column_12,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 menuCategories = Shape4(
      source: i0.VersionedTable(
        entityName: 'menu_categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_34,
          _column_35,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 menuEntries = Shape5(
      source: i0.VersionedTable(
        entityName: 'menu_entries',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_36,
          _column_15,
          _column_37,
          _column_38,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 ingredients = Shape6(
      source: i0.VersionedTable(
        entityName: 'ingredients',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_34,
          _column_39,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 recipes = Shape7(
      source: i0.VersionedTable(
        entityName: 'recipes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_40,
          _column_41,
          _column_42,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 purchaseScheduleItems = Shape8(
      source: i0.VersionedTable(
        entityName: 'purchase_schedule_items',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_36,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 expenses = Shape9(
      source: i0.VersionedTable(
        entityName: 'expenses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_51,
          _column_52,
          _column_25,
          _column_36,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 users = Shape10(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_53,
          _column_54,
          _column_55,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 sessions = Shape11(
      source: i0.VersionedTable(
        entityName: 'sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(token)',
        ],
        columns: [
          _column_56,
          _column_57,
          _column_58,
          _column_55,
          _column_12,
          _column_59,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 notifications = Shape12(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(type, date_key, meal_type)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_60,
          _column_61,
          _column_62,
          _column_63,
          _column_64,
          _column_65,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape15 appSettings = Shape15(
      source: i0.VersionedTable(
        entityName: 'app_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_66,
          _column_67,
          _column_68,
          _column_69,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_76,
          _column_77,
          _column_78,
          _column_79,
          _column_80,
          _column_81,
          _column_82,
          _column_83,
          _column_84,
          _column_89,
          _column_85,
          _column_86,
          _column_87,
          _column_88,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberId =>
      columnsByName['member_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lunchUnits =>
      columnsByName['lunch_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get breakfastUnits =>
      columnsByName['breakfast_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get brunchUnits =>
      columnsByName['brunch_units']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get paymentMethod =>
      columnsByName['payment_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get paymentStatus =>
      columnsByName['payment_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get billPdfPath =>
      columnsByName['bill_pdf_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get upiQrPath =>
      columnsByName['upi_qr_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reversed =>
      columnsByName['reversed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reversedAt =>
      columnsByName['reversed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reversedBy =>
      columnsByName['reversed_by']! as i1.GeneratedColumn<String>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
      from3To4: from3To4,
      from4To5: from4To5,
    ));
